"use client";
import { AnimatePresence, motion } from "motion/react";
import { HugeiconsIcon } from "@hugeicons/react";
import {
  SourceCodeIcon,
  ThirdBracketIcon,
  ThirdBracketSquareIcon,
  ThirdBracketCircleIcon,
  CollapseIcon,
  Copy01Icon,
  Tick02Icon,
} from "@hugeicons/core-free-icons";
import {
  type ComponentProps,
  createContext,
  type HTMLAttributes,
  type ReactNode,
  type RefObject,
  isValidElement,
  use,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import { cn } from "../lib/cn";
import { useCopyButton } from "@/lib/use-copy-button";

import { Tabs, TabsContent, TabsList, TabsTrigger } from "./ui/tabs";
import { mergeRefs } from "../lib/merge-refs";
import { Button } from "./ui/button";

const COPY_ICON_EASE = [0.33, 1, 0.68, 1] as const;

const copyIconMotion = {
  initial: { opacity: 0, scale: 0.8, filter: "blur(1px)" },
  animate: { opacity: 1, scale: 1, filter: "blur(0px)" },
  exit: { opacity: 0, scale: 0.8, filter: "blur(1px)" },
  transition: { duration: 0.15, ease: COPY_ICON_EASE },
} as const;

export interface CodeBlockProps extends ComponentProps<"figure"> {
  /**
   * Icon of code block
   *
   * When passed as a string, it assumes the value is the HTML of icon.
   * When omitted, a default code icon is shown.
   */
  icon?: ReactNode;

  /**
   * Allow to copy code with copy button
   *
   * @defaultValue true
   */
  allowCopy?: boolean;

  /**
   * Keep original background color generated by Shiki or Rehype Code
   *
   * @defaultValue false
   */
  keepBackground?: boolean;

  /**
   * Disable collapse behavior. When true, the code block shows full content
   * without max-height or "Show more" button.
   *
   * @defaultValue false
   */
  noCollapse?: boolean;

  viewportProps?: HTMLAttributes<HTMLElement>;

  /**
   * show line numbers
   */
  "data-line-numbers"?: boolean;

  /**
   * @defaultValue 1
   */
  "data-line-numbers-start"?: number;

  Actions?: (props: { className?: string; children?: ReactNode }) => ReactNode;
}

function languageFromClassName(className: unknown): string | undefined {
  const str =
    typeof className === "string"
      ? className
      : Array.isArray(className)
        ? className.filter((p): p is string => typeof p === "string").join(" ")
        : undefined;
  if (!str) return;
  const m = str.match(/\blanguage-([\w-]+)\b/);
  return m?.[1]?.toLowerCase();
}

/** Shiki leaves `language-*` on the inner `<code>`; MDX nests it under `<Pre>`. */
function findCodeLanguageInTree(node: ReactNode): string | undefined {
  if (node == null || typeof node === "boolean") return;
  if (typeof node === "string" || typeof node === "number") return;
  if (Array.isArray(node)) {
    for (const item of node) {
      const lang = findCodeLanguageInTree(item);
      if (lang) return lang;
    }
    return;
  }
  if (!isValidElement(node)) return;

  const props = node.props as { className?: unknown; children?: ReactNode };
  const lang = languageFromClassName(props.className);
  if (lang) return lang;

  return findCodeLanguageInTree(props.children);
}

const TabsContext = createContext<{
  containerRef: RefObject<HTMLDivElement | null>;
  nested: boolean;
} | null>(null);

export function Pre(props: ComponentProps<"pre">) {
  return (
    <pre
      {...props}
      className={cn("w-max min-w-full *:flex *:flex-col", props.className)}
    >
      {props.children}
    </pre>
  );
}

export function CodeBlock({
  ref,
  title,
  allowCopy = true,
  keepBackground = false,
  noCollapse = false,
  icon,
  viewportProps = {},
  children,
  Actions = (props) => (
    <div {...props} className={cn("empty:hidden", props.className)} />
  ),
  ...props
}: CodeBlockProps) {
  const inTab = use(TabsContext) !== null;
  const areaRef = useRef<HTMLDivElement>(null);
  const [expanded, setExpanded] = useState(false);
  const [overflows, setOverflows] = useState(false);

  const collapsedHeight = 16 * 24 + 28; // 16 lines × 24px line-height + 28px padding
  const showCollapse = !noCollapse && overflows && expanded;

  const codeLang = useMemo(() => findCodeLanguageInTree(children), [children]);
  const isJsonBlock =
    codeLang === "json" ||
    codeLang === "jsonc" ||
    (typeof title === "string" && /\.jsonc?$/i.test(title.trim()));

  const titleRowIcon =
    typeof icon === "string" ? (
      isJsonBlock ? (
        <HugeiconsIcon
          icon={ThirdBracketIcon}
          strokeWidth={2}
          className="-mb-0.5 size-4.25 shrink-0"
        />
      ) : (
        <div
          className="[&_svg]:size-3.5"
          dangerouslySetInnerHTML={{
            __html: icon,
          }}
        />
      )
    ) : icon != null ? (
      icon
    ) : (
      <HugeiconsIcon
        icon={isJsonBlock ? ThirdBracketSquareIcon : SourceCodeIcon}
        strokeWidth={2}
        className="-mb-0.5 size-4.25 shrink-0"
      />
    );

  const actionButtons = (
    <>
      {showCollapse && (
        <CollapseCodeButton
          onClick={() => {
            setExpanded(false);
            areaRef.current?.scrollTo({ top: 0 });
          }}
        />
      )}
      {allowCopy && (
        <CopyButton
          containerRef={areaRef}
          showGlow={!title}
          keepBackground={keepBackground}
        />
      )}
    </>
  );

  useEffect(() => {
    if (noCollapse) return;
    const el = areaRef.current;
    if (!el) return;

    const check = () => setOverflows(el.scrollHeight > collapsedHeight);
    check();

    const observer = new ResizeObserver(check);
    observer.observe(el);
    return () => observer.disconnect();
  }, [children, collapsedHeight, noCollapse]);

  return (
    <figure
      ref={ref}
      dir="ltr"
      {...props}
      tabIndex={-1}
      className={cn(
        inTab
          ? "-mx-px -mb-px bg-fd-secondary last:rounded-b-xl"
          : "my-4 rounded-xl dark:bg-background",
        keepBackground ? "" : "border border-gray-200 dark:border-white/10",
        "shiki not-prose relative overflow-hidden text-[13px] font-[450]",
        props.className,
        title && "bg-gray-100",
      )}
    >
      {title ? (
        <div className="flex h-9.5 items-center gap-2 px-4 text-fd-muted-foreground">
          {titleRowIcon}
          <figcaption className="flex-1 truncate font-mono">{title}</figcaption>
          {Actions({
            className: "-me-2 flex items-center gap-0.5",
            children: actionButtons,
          })}
        </div>
      ) : (
        Actions({
          className:
            "absolute top-3 right-3 z-2 flex items-center gap-0.5 rounded-lg text-gray-400 hover:text-gray-600 dark:text-gray-500 dark:hover:text-gray-300",
          children: actionButtons,
        })
      )}
      <div className="relative overflow-hidden rounded-xl bg-white dark:bg-gray-900">
        <div
          ref={areaRef}
          {...viewportProps}
          role="region"
          tabIndex={0}
          className={cn(
            "fd-scroll-container no-scrollbar overflow-auto overscroll-x-none rounded-t-xl px-4 py-3.5 text-sm leading-6 transition-[max-height] duration-300 ease-in-out focus-visible:ring-2 focus-visible:ring-fd-ring focus-visible:outline-none focus-visible:ring-inset",
            keepBackground
              ? "bg-gray-100! dark:bg-gray-950!"
              : "bg-white dark:bg-gray-900",
            viewportProps.className,
            overflows && expanded && "overflow-auto",
            overflows && !expanded && "overflow-hidden",
          )}
          style={
            {
              maxHeight: noCollapse ? "none" : expanded ? 615 : collapsedHeight,
              "--padding-right": !title
                ? "calc(var(--spacing) * 8)"
                : undefined,
              counterSet: props["data-line-numbers"]
                ? `line ${Number(props["data-line-numbers-start"] ?? 1) - 1}`
                : undefined,
              ...viewportProps.style,
            } as object
          }
        >
          {children}
        </div>
        {!noCollapse && overflows && !expanded && (
          <div className="absolute inset-x-0 bottom-0 flex h-60 items-end justify-center bg-linear-to-t from-[#999999] from-3% via-[#999999]/20 to-transparent dark:from-gray-950 dark:via-gray-950/90">
            <Button
              onClick={() => setExpanded(true)}
              className="mb-4 flex cursor-pointer items-center gap-1 rounded-full border-none bg-white px-3 py-1.5 text-sm font-medium text-gray-700 shadow-none transition-colors hover:bg-gray-100 hover:text-gray-900 dark:bg-gray-800 dark:text-gray-50 dark:hover:text-gray-300"
            >
              Show more
            </Button>
          </div>
        )}
      </div>
    </figure>
  );
}

function CollapseCodeButton({ onClick }: { onClick: () => void }) {
  return (
    <Button
      type="button"
      variant="ghost"
      size="icon-xs"
      className="mr-2.5 size-7 shrink-0 rounded-full text-gray-400 transition-colors hover:bg-transparent hover:text-gray-600 dark:text-gray-500 dark:hover:bg-transparent dark:hover:text-gray-300"
      aria-label="Show less"
      onClick={onClick}
    >
      <HugeiconsIcon icon={CollapseIcon} strokeWidth={2} className="size-4.5" />
    </Button>
  );
}

function CopyButton({
  className,
  containerRef,
  showGlow = false,
  keepBackground,
  ...props
}: ComponentProps<"button"> & {
  containerRef: RefObject<HTMLElement | null>;
  showGlow?: boolean;
  keepBackground?: boolean;
}) {
  const [checked, onClick] = useCopyButton(() => {
    const pre = containerRef.current?.getElementsByTagName("pre").item(0);
    if (!pre) return;

    const clone = pre.cloneNode(true) as HTMLElement;
    clone.querySelectorAll(".nd-copy-ignore").forEach((node) => {
      node.replaceWith("\n");
    });

    void navigator.clipboard.writeText(clone.textContent ?? "");
  });

  return (
    <div className="relative">
      {showGlow && (
        <div
          className={cn(
            "absolute top-1/2 left-1/2 z-0 size-13.5 -translate-x-1/2 -translate-y-1/2 rounded-l-full rounded-tr-full bg-linear-to-l",
            keepBackground
              ? "from-gray-100 from-70% to-gray-100/0 dark:from-gray-950 dark:to-gray-950/0"
              : "from-white from-70% to-white/0 dark:from-gray-900 dark:to-gray-900/0",
          )}
        ></div>
      )}
      <button
        type="button"
        data-checked={checked || undefined}
        className={cn(
          "relative flex size-7 cursor-pointer items-center justify-center rounded-full text-gray-400 transition-colors hover:text-gray-600 dark:text-gray-500 dark:hover:text-gray-300",
          className,
        )}
        aria-label={checked ? "Copied Text" : "Copy Text"}
        onClick={onClick}
        {...props}
      >
        <span className="relative flex size-5 items-center justify-center">
          <AnimatePresence mode="wait" initial={false}>
            {checked ? (
              <motion.span
                key="tick"
                {...copyIconMotion}
                className="flex items-center justify-center"
              >
                <HugeiconsIcon
                  icon={Tick02Icon}
                  strokeWidth={2}
                  className="size-4.5"
                />
              </motion.span>
            ) : (
              <motion.span
                key="copy"
                {...copyIconMotion}
                className="flex items-center justify-center"
              >
                <HugeiconsIcon
                  icon={Copy01Icon}
                  strokeWidth={2}
                  className="size-4"
                />
              </motion.span>
            )}
          </AnimatePresence>
        </span>
      </button>
    </div>
  );
}

export function CodeBlockTabs({ ref, ...props }: ComponentProps<typeof Tabs>) {
  const containerRef = useRef<HTMLDivElement>(null);
  const nested = use(TabsContext) !== null;

  return (
    <Tabs
      ref={mergeRefs(containerRef, ref)}
      {...props}
      className={cn(
        "rounded-xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-gray-950",
        !nested && "my-0",
        props.className,
      )}
    >
      <TabsContext
        value={useMemo(
          () => ({
            containerRef,
            nested,
          }),
          [nested],
        )}
      >
        {props.children}
      </TabsContext>
    </Tabs>
  );
}

export function CodeBlockTabsList(props: ComponentProps<typeof TabsList>) {
  return (
    <TabsList
      {...props}
      className={cn(
        "flex flex-row overflow-x-auto px-2 text-fd-muted-foreground",
        props.className,
      )}
    >
      {props.children}
    </TabsList>
  );
}

export function CodeBlockTabsTrigger({
  children,
  ...props
}: ComponentProps<typeof TabsTrigger>) {
  return (
    <TabsTrigger
      {...props}
      className={cn(
        "group relative inline-flex items-center gap-2 px-2 py-1.5 text-[13px] font-medium text-nowrap transition-colors hover:text-fd-accent-foreground data-[state=active]:text-fd-primary [&_svg]:size-3.5",
        props.className,
      )}
    >
      <div className="absolute inset-x-2 bottom-0 h-px group-data-[state=active]:bg-fd-primary" />
      {children}
    </TabsTrigger>
  );
}

export function CodeBlockTab(props: ComponentProps<typeof TabsContent>) {
  return <TabsContent {...props} />;
}
