export const SITE_URL = "https://nexus-ui.dev";
export const SITE_NAME = "Nexus UI";
export const SITE_TITLE = "Build Better AI Interfaces";
export const SITE_DESCRIPTION =
  "Open-source component library for building AI-native applications. Beautiful, composable primitives for chat, streaming, and multimodal experiences.";
export const SITE_DESCRIPTION_SHORT =
  "Beautiful, composable components for building AI-native applications.";
export const SITE_KEYWORDS = [
  "nexus ui",
  "nexus ui components",
  "nexus-ui",
  "@nexus-ui registry",
  "open source AI UI",
  "AI component library",
  "AI UI components",
  "AI-powered interfaces",
  "AI-native components",
  "composable AI components",
  "copy-paste AI components",
  "React AI components",
  "React 19",
  "Tailwind CSS v4",
  "TypeScript React components",
  "shadcn ui AI",
  "shadcn registry components",
  "shadcn CLI components",
  "chat interface components",
  "streaming chat UI",
  "streaming markdown UI",
  "multimodal chat UI",
  "composable chat input",
  "auto-resizing textarea",
  "chat message component",
  "chat thread component",
  "stick-to-bottom chat",
  "scroll-to-bottom control",
  "prompt input component",
  "prompt suggestion chips",
  "model selector component",
  "file attachments component",
  "chat attachments UI",
  "inline citation component",
  "inline source references",
  "hover preview citations",
  "reasoning component",
  "collapsible reasoning block",
  "chain of thought component",
  "multi-step thought timeline",
  "tool call UI",
  "text shimmer loading",
  "AI image component",
  "base64 image component",
  "image lightbox component",
  "feedback bar component",
  "message ratings UI",
  "Sonner toast notifications",
  "markdown chat message",
  "message markdown Streamdown",
  "streaming assistant output",
  "code block component",
  "nexus-ui-cli",
  "nexus ui skills",
  "llms.txt documentation",
  "Vercel AI SDK",
  "useChat UI components",
  "Streamdown markdown",
  "Radix UI chat components",
  "prompt input",
  "suggestions component",
  "copy-paste components",
  "Radix UI",
  "Tailwind CSS",
];
